version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: DB-Postgres
    environment:
      POSTGRES_USER: 'pedro'
      POSTGRES_PASSWORD: 'senha-postgres'
      POSTGRES_DB: DineExpress
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
